trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  mavenOptions: '-B -DskipTests'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
        options: '$(mavenOptions)'

- stage: Test
  jobs:
  - job: UnitTests
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        options: '-Dtest=*UnitTest'

  - job: RegressionTests
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        options: '-Dtest=*RegressionTest'
